### ISSUE TITLE
new website/blog/forum ?

### ISSUE THREAD

**Issue by alex-LE** [alex-LE/yourTinyTodo#13]
i think about creating a new website for myTinyTodo - as Max doesn't answer we may not be able to use mytinytodo.net (very sad)

**Comment by iGhost** [comment]
I think we should wait for Max's responce. Sometimes he is available.

**Comment by alex-LE** [comment]
ok, if you have any other contact than the email address from the website, please contact him

**Comment by maxpozdeev** [comment]
@alex-LE please write me at maxpozdeev@gmail.com

**Comment by alex-LE** [comment]
please have a look at issue #19
