### ISSUE TITLE
new themes

### ISSUE THREAD

**Issue by alex-LE** [alex-LE/yourTinyTodo#14]
i've seen a nice design of a todo list made with meteor, what do you think?

http://imageshack.us/photo/my-images/59/bildschirmfoto20120415u.png

is there anyone who can design a new theme? is there any need for this?

**Comment by iGhost** [comment]
nice, but as alternative :)

**Comment by alex-LE** [comment]
of course! ;-)

**Comment by alex-LE** [comment]
moved to forum (yourtinytodo.net/forum)
