### ISSUE TITLE
the future of this project - please discuss

### ISSUE THREAD

**Issue by alex-LE** [alex-LE/yourTinyTodo#19]
Hey, i've talked to Max. As it looks now, he will continue the project on his own. So we have 2 options:
1. stop here and let do Max the things he want
2. continue a community edition of myTinyTodo

I would prefer the second option. I can totally understand that Max wants to do the things he want. Its his project and when he doesn't want to work together, its his decision. So we will have 2 editions with maybe different features.
Max will have a look at the stuff we do here and merge some things into the original project and we might do the same.
So we should think about a website and maybe a better place to discuss features.

What do you think?

Alex

**Comment by alex-LE** [comment]
As discussed now with Max, we will have a community edition of myTinyTodo called "myTinyTodo+" located at the subdomain plus.mytinytodo.net.
We will also set up a forum for both versions, url will follow.

**Comment by jniggemann** [comment]
Wow, what's going on here? I just stumbled across this thread by pure chance while surfing..
I was never aware of the fact that MTT was more than a one man show, although I use it since years!
I don't have much time (family, job, ...) but I'd like to contribute - what do you need, how can I help?

**Comment by alex-LE** [comment]
great, i think we can build up a great community - you may contact me at info@alexander-adam.net

**Comment by iGhost** [comment]
The second option is good!
Will help to build MTT+.

Also thank you Max for MTT!
And thank you Alex for the second breath to MTT :)

**Comment by alex-LE** [comment]
We've decided to create a community Edition of MTT called yourTinyTodo. The new website yourtinytodo.net is running (we currently work on the site and maybe use another system) and we've set up a forum for both projects as well -> yourtinytodo.net/forum (feel free to register and discuss stuff there - we will move the issues from github to the forum soon)
