### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by jniggemann** [alex-LE/yourTinyTodo#21]
Can we integrate the these language files or are they too old?
http://code.google.com/p/mytinytodo/source/browse/langs/?r=216815b3fc0592c5dfe4aec62d9d5c42c7df9216
Perhaps we can contact the authors and ask if they have updated versions...

**Comment by alex-LE** [comment]
please move that into the forum :P

**Comment by jniggemann** [comment]
--> http://www.yourtinytodo.net/forum/index.php?topic=4.0
