### ISSUE TITLE
Exception: 'no such function: CONCAT' in class.db.sqlite3.php:39

### ISSUE THREAD

**Issue by nansenat16** [alex-LE/yourTinyTodo#28]
I try upgrade from 1.4.2 to dev on multiuser mode when I login get this error.
In ajax.php line 301:

```
        $result = $db->dq("SELECT role,id FROM {$db->prefix}users WHERE username = ? AND MD5(CONCAT(?,uuid)) = password", array($username, $password) );
```

And On https://github.com/alex-LE/yourTinyTodo/blob/develop/setup.php#L422
It cna't upgrade any version.

**Comment by alex-LE** [comment]
thanks for the hint, issue fixed
