### ISSUE TITLE
better git support for code upgrade

### ISSUE THREAD

**Issue by sokai** [alex-LE/yourTinyTodo#32]
Hi!

I'm not a git-pro but I upgrade my yTT by „git pull“ on my server. Thereby I notice the problem, that my changes to 'db/todolist.db' and 'db/config.php' prevents a successful „git pull“.

I think changing 'db/todolist.db' to 'db/todolist.sample.db' and 'db/config.php' to 'db/config.sample.php' can resolve the problem. – Is it possible?

Thanks and best regards!

**Comment by alex-LE** [comment]
Sure, we've already discussed that. I have the same problem during development. We will change that soon.
We've also planned a update function, so that you don't need to update it via github, but that will be in the future.

**Comment by sokai** [comment]
Thanks Alex for your fast reply!

Do you think it's a good idea to make a “Pull Request“ for that renaming thing? (No matter if the code changes will become permanent or temporary…) – I could do that.

Concerning the update procedure…: Good idea. But at the moment I'm on the „development“ tree which probably isn't upgradeable…

**Comment by alex-LE** [comment]
Sure, feel free to make a pull request! Its a community project, not my own ;-)

I think the update function should only for for releases, the development changes should be updated with git.

**Comment by alex-LE** [comment]
I've done it now, as it should be part of the release comming soon
