### ISSUE TITLE
Some shortcuts/macros would be nice for priorities and tags

### ISSUE THREAD

**Issue by darklow** [alex-LE/yourTinyTodo#38]
First of thanks for taking over and improving this nice todo lists.

It would be nice if we could specify priority and tags using some kind of shortcuts/macros syntax for example if macroses are enabled (it could be in settings) then you could type in "New task input" something like:
`My new precious task +1 #tag #tag2`

Otherwise it is quite annoying after every new task go inside and add priority or tags, also right button is helpful if you want to change something fast for existing task, but also annoying doing it for every task.

Thanks

**Comment by jniggemann** [comment]
This already exists, it's called "smart syntax". Enter your tasks in this format:
/Priority/ Task /Tags/
/2/ My Important Task /Tag1, Tag2/
