### ISSUE TITLE
Is it possible to see also completed tasks?

### ISSUE THREAD

**Issue by darklow** [alex-LE/yourTinyTodo#39]
Is it possible to see also completed tasks somewehere? 
To set option to see all the tasks, or some kind of an archive? Could't find it.
I accidentally chosen wrong checkbox and want to make it as undone again.

Thank you.

**Comment by alex-LE** [comment]
Sure, there is a small arrow next to the tab name (on the right side). You
will find a option in the menu to show completed tasks.

2012/10/1 Kaspars Sprogis notifications@github.com

**Comment by darklow** [comment]
Thanks
