### ISSUE TITLE
Editing Tasks in "Advanced mode" broken

### ISSUE THREAD

**Issue by hebbet** [alex-LE/yourTinyTodo#41]
When you open a task eg to add a tag and it save you will get "Some error occurred"

**Comment by hebbet** [comment]
tested with current trunk Version (1.0a) on chrome and Firefox stable with no extensions.

**Comment by alex-LE** [comment]
I couldn't reproduce it yet.
Could you please try it on the demo site: http://alexphpc.my.phpcloud.com/yourtinytodo/ and send me some screenshots?

**Comment by hebbet** [comment]
see:
http://images.pascal90.de/Screenshot-from-2012-11-03-171307.png

**Comment by alex-LE** [comment]
Ok, it was a missing column in the database. I've updated the demo and fixed that in the master branch.
thanks for the info!
