### ISSUE TITLE
Duration Timer should support minutes

### ISSUE THREAD

**Issue by hebbet** [alex-LE/yourTinyTodo#44]
Some tasks may online need a few minutes to be done. so the timer should support eg Duration 10 minutes too

**Comment by alex-LE** [comment]
Its possible to add for example 0.1 hours, but its a little bit more difficult to get the right value ;-)

**Comment by hebbet** [comment]
yes, i knew it.

just mark it as feature request/enhancement ;)

**Comment by alex-LE** [comment]
please have a look at the latest develop version
