### ISSUE TITLE
Exception: author may not be NULL

### ISSUE THREAD

**Issue by jniggemann** [alex-LE/yourTinyTodo#49]
Hi Alex,

found a bug in the latest DEV version, reproduce like this:
- Get latest dev version
- open web browser, run setup (sqlite)
- open freshly installed YTT, try to add task

=> Exception: 'ytt_todolist.author may not be NULL' in /var/www/ytt-dev/core/db/class.db.sqlite3.php:46

**Comment by alex-LE** [comment]
thanks, fixed
