### ISSUE TITLE
Soft delete for Tasks

### ISSUE THREAD

**Issue by Chumper** [alex-LE/yourTinyTodo#50]
Instead of deleting task i would supose to soft delete them and 
1. put them in a new list "Closed"
or
2. Add them under all open Tasks as "closed"

You could set this in the settings, and have the ability to see all closed tasks.

**Comment by Chumper** [comment]
Alright, nevermind, i found the option :)

**Comment by alex-LE** [comment]
no worries! :D

**Comment by tmos** [comment]
But it is true, the option could be easier to found :+1:
