### ISSUE TITLE
Advanced editing on create broken

### ISSUE THREAD

**Issue by hebbet** [alex-LE/yourTinyTodo#52]
in the latest developer version it is not possible to add a note on creation of the task.

repro
- install latest dev version
- enter text into new task
- hit the icon with the pencil
- click save

you are getting:
Some error occurred

**Comment by alex-LE** [comment]
thanks for the hint, its fixed

**Comment by hebbet** [comment]
introduced a small new bug: Inserts "by undefined" after task name and undefined in hour and minutes.

**Comment by alex-LE** [comment]
I've fixed some small stuff, but i don't think this was the issue. Could you please send me a screenshot?

**Comment by hebbet** [comment]
i only changed the file you updated

on a fresh install it was ok. Maybe i should re-run the setup.php
