### ISSUE TITLE
PHP Fatal error:  Interface 'IDatabaseResult' not found

### ISSUE THREAD

**Issue by 0x646e78** [alex-LE/yourTinyTodo#58]
Upon running setup.php a blank page is presented after selecting the desired database.

Apache error.log shows:
PHP Fatal error:  Interface 'IDatabaseResult' not found in /srv/www/DOMAIN/public_html/yourTinyTodo/core/db/class.db.sqlite3.php on line 13, referer: http://DOMAIN/yourTinyTodo/setup.php

Environment:
Centos 6.4
Apache 2.2.15
php 5.3.3

I will look into this further this week, however my PHP is not awesome so maybe someone will beat me to finding a fix for this.

As an aside I am successfully running myTinyTodo.

**Comment by alex-LE** [comment]
Which version did you tried? The latest from develop branch?

Alex

**Comment by 0x646e78** [comment]
Hi Alex. Yeah, I just git-cloned the repo.

**Comment by 0x646e78** [comment]
I should also note that this same behaviour is apparent with both mysql and sqlite
