### ISSUE TITLE
Archive Lists - menu item for all tasks stays greyed out.

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#60]
When switching between the archives and all tasks lists the option to go back to all tasks is greyed out, and the archive item is still checked but you can't select it.

**Comment by alex-LE** [comment]
Could you please try it again with the latest dev version? I'm not sure if it is still there as i've made some changes.

**Comment by electricmessiah** [comment]
It seems to work better now, but I still have to click archive a few times before the update occurs.

**Comment by electricmessiah** [comment]
I also noticed that if there are no archived tabs and you select the archive menu item you get the same greyed out issue. Might as well disable the item if there are no tabs archived.

**Comment by alex-LE** [comment]
this might be fixed now

**Comment by electricmessiah** [comment]
Confirmed Fix
