### ISSUE TITLE
Check mark not removed when switching from archive to active view

### ISSUE THREAD

**Issue by jniggemann** [alex-LE/yourTinyTodo#61]
Can be reproduced in latest dev:
open ytt, click archived lists -> only archived lists are displayed and a 'archived lists' has a checkmark.
Now, click on archived lists once more. The "active" lists are displayed, but the checkmark next to 'archived lists' stays.

**Comment by alex-LE** [comment]
fixed

**Comment by jniggemann** [comment]
fix confirmed

**Comment by electricmessiah** [comment]
I still have to click archives twice from time to time before the update occurs.

**Comment by jniggemann** [comment]
4897535bac fixes problem,  confirmed. Can't reproduce drodgersfoms issue.

**Comment by electricmessiah** [comment]
https://github.com/alex-LE/yourTinyTodo/commit/4897535bac - Is an icon reference. ;)

**Comment by jniggemann** [comment]
Yeah, got that one wrong :-)
