### ISSUE TITLE
Published lists produce an index error if not logged in

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#62]
If you have lists published, an error occurs when you visit the page without being logged in. If you log in everything is fine. If you set the app to operate in single user it seems fine.

Notice: 'Undefined index: userid' in /home/tasks/ajax.php:1209 #0 /home/tasks/ajax.php(1209): myErrorHandler(8, 'Undefined index...', '/home/tasks/...', 1209, Array) #1 /home/tasks/ajax.php(38):

**Comment by alex-LE** [comment]
fixed
