### ISSUE TITLE
Archive checkmark stays after returning to non-archived list

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#65]
When switching to the archived list everything looks good, but switching back to the list of unarchived tabs retains a checkmark next to archived. This occurs on all tabs that are not archived.

**Comment by jniggemann** [comment]
First of all, this is a duplicate of https://github.com/alex-LE/yourTinyTodo/issues/61
and secondly, I can't reproduce when using latest dev (4897535bac at the time of writing).

Are you 100% sure you used the latest dev?

**Comment by electricmessiah** [comment]
I loaded the latest dev again and you're correct. All seems to be working.
