### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#66]
There are a few icons missing. 

images/loading1.gif
images/inprogress_icon.gif
tagcloudload - images/loading1_24.gif

**Comment by alex-LE** [comment]
thanks for the hin, i've readded them

**Comment by electricmessiah** [comment]
np. thanks for all of your contributions.

**Comment by electricmessiah** [comment]
Found a few more:

style_rt.css (16,17)
url(images/tab_hover.gif)
url(images/corner_left.gif)

**Comment by alex-LE** [comment]
fixed
