### ISSUE TITLE
multiuser support

### ISSUE THREAD

**Issue by alex-LE** [alex-LE/yourTinyTodo#7]
see http://goo.gl/eUIFi

**Comment by alex-LE** [comment]
work is done, testing now

**Comment by iGhost** [comment]
Wow really? :) nice!

**Comment by alex-LE** [comment]
yes :) - i will upload it soon to phpcloud.com for some testing, profile, ...
If you want i can send you the link

**Comment by iGhost** [comment]
Yeah sure. Will help to test it out.

**Comment by alex-LE** [comment]
uploaded to: http://alexphpc.my.phpcloud.com/mytinytodo

I don't know why but it crashs my Firefox (latest version) on Windows, on Mac Firefox works, Chrome also

**Comment by iGhost** [comment]
mine doesn't. Everything ok. FF, Chrome, Opera, Safari on Win XP.

when logged in as read only user and editing content of record it is confusing when "Save" button pressed and there is no any responce.
On main view  "Access denied" is displayed.

**Comment by alex-LE** [comment]
i'll fix that, thanks

**Comment by alex-LE** [comment]
fixed - i've disabled the double click function when not logged in as admin or read/write user

**Comment by kilolife** [comment]
Error during clean setup. development 1.5 version
in file setup.php (two incoming - line 408 and 1049): 
$db->ex("INSERT INTO {$db->prefix}users``(`id`,`uuid`,`username`,`password`,`email`,`d_created`,`role`) VALUES (1, '".$uuid."', 'admin', '".hashPassword('admin',$uuid)."', 'mail@example.com', ".time().", '1')");

wrong SQL syntax. Bad quote after {$db->prefix}users

And please add an option to display only my own notes. As well as the ability to designate the owner of the notes of another user. And get a perfect system. I feel that we are just a few steps from it.
And sorry for my bad English.

**Comment by alex-LE** [comment]
@kilolife bug fixed (including some others) - setup seems to work now
-> i've moved your feature request to a single issue
