### ISSUE TITLE
TimeTable still working?

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#70]
I also haven't been able to get the highcharts graph to show.

I've also seen an HTTP: 500/Internal Server Error when clicking the timetable for a list.

**Comment by electricmessiah** [comment]
In timetable.php it looks like there are quite a few open php tags <? that should be <?php. And shouldn't the =$var tags be echo $var?

**Comment by alex-LE** [comment]
fixed, it seems that php doesn't like no space arround braces ;)

<?= is a short version for <? echo ...
But this works on PHP < 5.4. with short_open_tags enabled only

**Comment by electricmessiah** [comment]
The highcharts pie chart is not rendering properly, and the times are not correct. This is on latest dev with Chrome, IE, Firefox.

**Comment by alex-LE** [comment]
fixed

**Comment by electricmessiah** [comment]
confirmed fix
