### ISSUE TITLE
Large whitespace below task list

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#73]
I've noticed this large white space that pushes the footer with the copyright down. 

< div id="taskajax" >< /div > with a min height of 400px

Is there a quick fix to remove this space?

**Comment by alex-LE** [comment]
done

**Comment by electricmessiah** [comment]
Whitespace is gone, but the footer is still way down the page. This causes a scrollbar to appear even if we don't need to scroll.

**Comment by alex-LE** [comment]
Which browser are you using?

**Comment by jniggemann** [comment]
Latest dev:
This is because the margin-top of #footer is -28px and its height is 30px...
So there's always 2px "further down", causing a vertical scrollbar to appear.

**Comment by electricmessiah** [comment]
To fix what I'm seeing (tested on IE10, Chrome, Firefox):

Remove min-height: 100% from #container.
Change #space to { height: 20px; }
You can leave the min-height 400px in #taskajax.

There is a small issue in IE where the hover selection of the (all tasks, archive, etc) is all white so you can't see the currently selected item. IE isn't resolving the blue background color properly. Not sure if an IE hack is needed, I wouldn't think so with IE10, so might just need some element tweaks to get it right.

It'll be around line 919 of styles.css. I've been messing around with no luck so far.

**Comment by alex-LE** [comment]
fixed both issues

**Comment by electricmessiah** [comment]
confirmed fix
