### ISSUE TITLE
Tasks disappear when markdown is enabled

### ISSUE THREAD

**Issue by electricmessiah** [alex-LE/yourTinyTodo#75]
The latest commit works fine after install, but if I point the config to my database of existing tasks the tasks show up when markdown is disabled, but enabling it causes the list to appear empty. Disable and they show back up. 

UPDATE: This is tested on the latest commit. If you enter a task without going into the editor the task will not show up, but it will be reflected in the count. If you enter tasks via the editor they work fine.

UPDATE: This is tested on the latest commit. If you disable/enable markdown the list will go blank. There are some issues with the markdown integration that is causing list issues.

**Comment by alex-LE** [comment]
you're right, there was a issue with empty notes, it should be fixed

**Comment by electricmessiah** [comment]
Confirm Fix

**Comment by alex-LE** [comment]
great
