### ISSUE TITLE
mail notification about new/modified tasks

### ISSUE THREAD

**Issue by alex-LE** [alex-LE/yourTinyTodo#8]
will be great to get a info when some adds or modifies a task

**Comment by iGhost** [comment]
How would you do that?
It is too slow to send mail right after some action.
Maybe Minutely cron job?

**Comment by alex-LE** [comment]
You're right, sending an email right after each action may be too much and too slow.
Maybe something like Facebook do, 1 email per day with a summary of all actions?
Or mails only for new tasks and maybe subscribed ones?

**Comment by iGhost** [comment]
I think it is ok to check for pending mail every minute and send it using cron job

**Comment by jniggemann** [comment]
I like the idea of mail notifications, but let's not forget that quite a lot of hosters don't allow cronjobs...

**Comment by iGhost** [comment]
So you have any other suggestions?

**Comment by jniggemann** [comment]
Perhaps we could implement it the way drupal does: Put the cron tasks in a php script.
The script can then be called by cron (where possible) or by calling its URL (that way people can use external cron providers like cron-job.org or cronjobs.de).
What do you think?

**Comment by alex-LE** [comment]
What about sending a email directly after something happens (new task, task edited ...). But only one mail until the user has open ytt. We can create a notification list (like github has). So the user won't get any more mails until he has visited the list.
We need no cron and do not flood the mailbox.

**Comment by alex-LE** [comment]
we should move that discussion into the forum, thats what it is for :P

**Comment by iGhost** [comment]
> Put the cron tasks in a php script.
> The script can then be called by cron (where possible) or by calling its URL (that way people can use external cron providers like cron-job.org or cronjobs.de).

This is what the `cron` is.
Of course it's a php script called by any (internal/external) cron

**Comment by jniggemann** [comment]
@iGhost Hmm... I see. I had no idea we were talking about the same thing :-)
Can you implement something like that?

I really like Alex idea to send a single mail and have a notification list like github does, but won't that be quite a lot of work?

**Comment by alex-LE** [comment]
I don't think so, if you want to send the changes via cronjob, you have to collect/save them anyway. With the notification list the user won't get emails every day/hour (depends on the cron).

**Comment by jniggemann** [comment]
If it's not more difficult I'll prefer it that way...

**Comment by alex-LE** [comment]
please lets move this discussion to the forum (we need to get more stuff there)

http://www.yourtinytodo.net/forum/index.php?topic=7.0
