### ISSUE TITLE
XSS vulnerability in comments

### ISSUE THREAD

**Issue by ghost** [alex-LE/yourTinyTodo#88]
Hi

I wrote `<script>alert('xss');</script>` in a comment, and the script is loaded...

![capture decran 2013-10-09 a 09 21 33](https://f.cloud.github.com/assets/1587933/1295604/7a2d713c-30b3-11e3-9488-c6ae78d68169.png)

**Comment by alex-LE** [comment]
thanks, i've fixed it

**Comment by ghost** [comment]
You're welcome :)
